spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?createDatabaseIfNotExist=true
    username: root
    password: 80221474
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  couchbase:
    env:
      timeouts:
        connect: 3000
        view: 75
server:
  port: 8080
  servlet:
    context-path: /security

jwt:
  secret: savinda
  expiration: 86400000